### ISSUE TITLE
Would you please open the source code of this paper?

### ISSUE THREAD

**Issue by Imorton-zd** [lancopku/Seq2Set#1]
Congratulations for this accepted ACL2019 paper. I am very interesting in multi-label text classification and have learnt a lot from your previous works, such as SGM. I am looking forward to the source code of the above acl paper. Thanks!

**Comment by JaeZheng** [comment]
Congratulations for this accepted ACL2019 paper, too. Your previous works in MLTC like SGM and SU4MLC caught my interest, including this proposed Seq2Set model. Would you please open the source code of this paper? I am also looking forward to the source code of this model. Thanks!
