### ISSUE TITLE
您好，我对你的代码很感兴趣，我在你的代码中，没能找到mask已经预测出来的标签，但是我在你论文中看到了

### ISSUE THREAD

**Issue by cm-xcju** [lancopku/Seq2Set#3]
我使用的是RCV数据集

**Comment by cm-xcju** [comment]
在decoder预测过程中，后面预测的标签理应该和前面的标签不重复，但是我看了代码，预测的结果我也查看过了，里面有很多重复的标签

**Comment by ypengc7512** [comment]
Be sure to use the MLE method to pre-train the model and use -restore to load the pre-trained checkpoint. I will update the code in the next few days.

**Comment by cm-xcju** [comment]
Thankyou for your suggestion
